### PR TITLE
adds Visitor pattern, implements Printer for Components and updates b…

### PR DESCRIPTION
**Pull request by ghost**
…asic test

### CODE REVIEW

**Comment by mengelbrecht** [comment]
Please run clang-format on your changes, the indentation is tabs instead of spaces.

Also when building this on OS X with clang from Xcode 7.2 it yields the following warnings and errors:

```
FAILED: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -I../include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk   -std=gnu++11 -MMD -MT test/CMakeFiles/test_basic.dir/basic.cpp.o -MF test/CMakeFiles/test_basic.dir/basic.cpp.o.d -o test/CMakeFiles/test_basic.dir/basic.cpp.o -c ../test/basic.cpp
In file included from ../test/basic.cpp:8:
../include/kompositum/printer.h:17:21: warning: length modifier 'I64' results in undefined behavior or no effect with 'd' conversion specifier [-Wformat]
                printf ("- Leaf (%I64d)\n", leaf->getID ());
                                 ~^~~~
../include/kompositum/printer.h:27:27: warning: length modifier 'I64' results in undefined behavior or no effect with 'd' conversion specifier [-Wformat]
                        printf ("- Composite (%I64d): empty\n", composite->getID ());
                                              ~^~~~
../include/kompositum/printer.h:31:27: warning: length modifier 'I64' results in undefined behavior or no effect with 'd' conversion specifier [-Wformat]
                        printf ("+ Composite (%I64d):\n", composite->getID ());
                                              ~^~~~
../test/basic.cpp:27:20: error: non-const lvalue reference to type 'Kompositum::Visitor' cannot bind to a temporary of type 'Kompositum::Printer'
        composite.accept (Printer ());
                          ^~~~~~~~~~
../include/kompositum/composite.h:21:24: note: passing argument to parameter 'visitor' here
        void accept (Visitor& visitor) override { visitor.visit (this); }
                              ^
```

**Comment by ghost** [comment]
So, I will merge it. Thanks for the CI ;)

**Comment by mengelbrecht** [comment]
It seems like your clang-format did not use the file in the repository. For example the indentation of your files is only 2 spaces instead of 4.

**Comment by ghost** [comment]
Ups, I used the official clang format Visual Studio plugin and set the file. Hmm. Can you commit the right format? I need to take a deeper look into it. Thanks for the feedback.

**Comment by mengelbrecht** [comment]
Fixed with 001d22d

**Comment by rehans** [comment]
I also use the MSVS plugin.

Go to: Tools >> Options... >> LLVM/Clang and put "Style" to "file". This should do the trick :)

**Comment by ghost** [comment]
Okay, I mixed it up in the options. Thanks again.

**Pull request merged**
